USE health_db;

-- 插入你刚才添加到 images 文件夹的所有图片
INSERT INTO `resource` (`type`, `title`, `content`) VALUES 
(2, '下午茶', '/images/下午茶.jpg'),
(2, '落叶风景', '/images/落叶风景.jpg'),
(2, '鸟语花香', '/images/鸟语花香.jpg'),
(2, '草原风景', '/images/草原风景.jpg'),
(2, '灯塔', '/images/灯塔.jpg'),
(2, '果园风景', '/images/果园风景.jpg'),
(2, '美味点心', '/images/美味点心.jpg'),
(2, '湖边小镇', '/images/湖边小镇.jpg'),
(2, '温馨小屋', '/images/温馨小屋.jpg'),
(2, '浪漫情侣', '/images/浪漫情侣.jpg'),
(2, '都市夜景', '/images/都市夜景.jpg'),
(2, '治愈小屋', '/images/治愈小屋.jpg'),
(2, '沙滩小镇', '/images/沙滩小镇.jpg'),
(2, '旅游', '/images/旅游.jpg'),
(2, '美好家庭', '/images/美好家庭.jpg'),
(2, '温馨家庭', '/images/温馨家庭.jpg'),
(2, '幸福家庭', '/images/幸福家庭.jpg'),
(2, '跑步', '/images/跑步.jpg'),
(2, '可爱红花', '/images/可爱红花.jpg'),
(2, '小路风景', '/images/小路风景.jpg'),
(2, '户外景色', '/images/户外景色.jpg'),
(2, '户外风景', '/images/户外风景.jpg'),
(2, '小亭风景', '/images/小亭风景.jpg'),
(2, '湖面小桥风景', '/images/湖面小桥风景.jpg'),
(2, '可爱小孩', '/images/可爱小孩.jpg'),
(2, '可爱小猫', '/images/可爱小猫.jpg'),
(2, '可爱少女', '/images/可爱少女.jpg'),
(2, '可爱泰迪', '/images/可爱泰迪.jpg'),
(2, '可爱小狗', '/images/可爱小狗.jpg'),
(2, '可爱猫咪', '/images/可爱猫咪.jpg'),
(2, '可爱哈吉米', '/images/可爱哈吉米.jpg'),
(2, '可爱小猫咪', '/images/可爱小猫咪.jpg'),
(2, '可爱萌萌猫', '/images/可爱萌萌猫.jpg');
